#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}
demo=${PUBQR_DEMO}

# until nc -z -v -w30 mysql 3306
# do
#     echo "Waiting for database connection..."
#     sleep 5
# done

until echo 'PING' | nc -w 1 redis 6379 | grep -q PONG
do
    echo "Waiting for Redis connection..."
    sleep 5
done

php /var/www/html/artisan config:cache

if [ "$role" = "app" ]; then
    touch /database/database.sqlite
    chown -R www-data /database
    php artisan migrate
    if [ -n "$demo" ]; then
        php artisan pubqr:createdemodata
    fi
    php artisan pubqr:createadmin
    exec apache2-foreground

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
