#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

# until nc -z -v -w30 mysql 3306
# do
#     echo "Waiting for database connection..."
#     sleep 5
# done

until echo 'PING' | nc -w 1 redis 6379 | grep -q PONG
do
    echo "Waiting for Redis connection..."
    sleep 5
done

php /var/www/html/artisan config:cache

if [ "$role" = "app" ]; then
    touch database/database.sqlite
    php artisan migrate
    exec apache2-foreground

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
